### ISSUE TITLE
Pregledanje rada

### ISSUE THREAD

**Issue by danilo1996** [MATF-RG17/RG092-simulacije-sa-kockicama#1]

**Comment by ivan-cukic-matf** [comment]
Otvorite ovaj issue kad zavrsite #2 i #3

**Comment by danilo1996** [comment]
Dodao sam Makefile i dodao sam upustvo kako se koristi.

**Comment by ivan-cukic-matf** [comment]
Kad implementirate #4, otvorite ovaj issue opet
